baseURL = 'https://example.org/'
locale = 'en-us'
title = 'belladonna sherum, innollia, 결망아안, 이충호, 혹은하나의일'
theme = 'hugo-trainsh'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
mainSections = ["posts"]
nav = "[Home](/) [posts](/posts/)"